title: Kelsey McKenna
tagline: Blog about software and stuff
description: >-
  This is my blog and site for posts about computer science, software engineering, mathematics and more.
baseurl: ""
url: "https://kelseymckenna.com"
twitter_username: ToastNumber
github_username: ToastNumber
linkedin_username: KelseyMcKenna

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
theme: minima
paginate: 5
show_excerpts: true
excerpt_separator: "<!--more-->"

plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap

defaults:
  - scope:
      path: "./google*.html"
    values:
      sitemap: false
  - scope:
      path: "./resources/**"
    values:
      sitemap: false

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/

